export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const COUNTRIES_LOADED = 'COUNTRIES_LOADED';
export const COUNTRIES_LOAD_FAILURE = 'COUNTRIES_LOAD_FAILURE';
export const GET_DETAILS = 'GET_DETAILS';
export const OPEN_INFO = 'OPEN_INFO';
export const CLOSE_INFO = 'CLOSE_INFO';
